#!/bin/sh
ver0=`cat version.h |grep VERSION_MAJOR|cut -c 23-23`
ver1=`cat version.h |grep VERSION_MINOR|cut -c 23-23`
ver2=`cat version.h |grep PATCHLEVEL|cut -c 20-20`
ver3=`cat version.h |grep EXTRAVERSION|cut -c 23-30`
FVERSION="${ver0}.${ver1}.${ver2}${ver3}"
cp -R ../fidogate fidogate${FVERSION}
rm -rf ./${FVERSION}/test
tar cvf fidogate${FVERSION}.tar fidogate${FVERSION}
rm -rf fidogate${FVERSION}
bzip2 -v9 fidogate${FVERSION}.tar
