.TH leafnode-group 1 "Maint Laboratory" "Linux" "Maint Laboratory"
.SH ИМЯ
leafnode-group \- Работа с группами новостей для leafnode
.SH СИНТАКСИС
leafnode-group [-options] [groupname]
.SH ОПИСАНИЕ
Позволяет производить манипуляции с группами новостей NNTP сервера leafnode.
.SH ОПЦИИ
.TP
.I -v
болтливый режим
.TP
.I -h
помощь
.TP
.I -l
получить список групп с сервера
.TP
.I -m
создать обычную группу
.TP
.I -M
создать обычную группу и активизировать ее
.TP
.I -o
создать локальную группу
.TP
.I -a
сделать группу активной
.TP
.I -d
сделать группу неактивной
.TP
.I -r
удалить группу
.TP
.I -с
проверка существования группы новостей
.TP
.I -L
создать файл inn active
.SH СМОТРИ ТАКЖЕ
rnews(1), leafnode(8), send-fidogate(1)

