.TH send-fidogate 1 "Maint Laboratory" "Linux" "Maint Laboratory"
.SH ИМЯ
send-fidogate \- гейт из leafnode в fidogate
.SH СИНТАКСИС
send-fidogate [-h] [-v]
.SH ОПИСАНИЕ
Позволяет отправить сформированные сообщения NNTP сервера leafnode в fidogate.
.SH ОПЦИИ
.TP
.I -v
болтливый режим
.TP
.I -h
помощь
.SH СМОТРИ ТАКЖЕ
m2news(1), leafnode(8), rnews(1)
