#!/bin/sh

../tr.init

A="../../src/areafix/ftnafpkt -c../cf/fidogate.conf -vvv"
O="../../src/util/ftnoutpkt   -c../cf/fidogate.conf -vvv"
F="../../src/areafix/ftnaf -vvv"
D="../../src/util/pktdebug    -t"


T="../../src/gate/rfc2ftn -c../cf/fidogate.conf -vvv"
D="../../src/util/pktdebug"

echo "tc: running"

# Testing aka matching

$T                                   Any@f129.n5030.z2.fidonet.org  <body1
$T -a 2:5030/468.999                 Any@f468.n5030.z2.fidonet.org  <body1
$T                   -u 2:5030/468.0 Any@f468.n5030.z2.fidonet.org  <body1
$T                                   Any@f468.n5030.z2.fidonet.org  <body1
$T                                   Any@f1251.n12.z526.z526.org    <body1
$T                                   Any@f1.n168.z192.z192.org      <body1
$T                                   Any@f126.n50.z2.z2.org         <body1
$T -n                                Any@f126.n5030.z2.z2.org       <body1
$T -n                                Any@f126.n50.z2.fidonet.org    <body2

cp config config.tmp

echo "1234567890fido/ru/linux/1" > batch.tmp
echo 10 > batch.tmp.pos

$T -f ./batch.tmp -c config.tmp

echo "NoFromLine"   >> config.tmp
echo "NoChrsKludge" >> config.tmp
$T -n  -c config.tmp  <newsspool/fido/ru/linux/1

$D -t outpkt/*/*.pkt

# NoFSC0035
# NoFSC0035ifAlias
# NoFSC0047
# MaxMsgSize X
# LimitMsgSize X
# EchoMail4D
# HostsRestricted
# RFCLevel (1-3)
# XFlagsPolicy N|S|A
# DontUseReplyTo
# RFCAddrMode ()|<>
# ReplyAddrIfmailTX
# CheckAreasBBS
# AreasBBS (newsmode || CheckAreasBBS)
# UseXHeaderForTearline
# NoRfcKludge
# NoGatewayKludge
# AddressIsLocalForXPost
# DefaultCharset
# NetMailCharset
# DontChangeContentTypeCharset
# DontProcessReturnReceiptTo
# XFromKludge
# NoLogIfArticleNotFound
# DontFlushDBCHistory
# EchogateAlias