# 
#	Makefile for Xmonout an outbound monitor for X
#		
#
# change the directory below to where you keep your binaries for fidogate

all : 

	install -o news -g news xmonout /usr/local/lib/fidonet
	install -o news -g news monout /usr/local/lib/fidonet
	install -o news -g news xoutfix /usr/local/lib/fidonet



