/* Automatically generated by subst.pl --- DO NOT EDIT!!! */

/*
 * FIDOGATE
 *
 * $Id: cf_abbrev.mak,v 4.19 2003/04/15 18:45:25 n0ll Exp $
 */

{ 'K', cf_p_lockdir },
{ 'V', cf_p_vardir },
{ 'U', cf_p_uuinbound },
{ 'P', cf_p_pinbound },
{ 'L', cf_p_libdir },
{ 'I', cf_p_inbound },
{ 'N', cf_p_bindir },
{ 'C', cf_p_configdir },
{ 'B', cf_p_btbasedir },
{ 'S', cf_p_spooldir },
{ 'G', cf_p_logdir },
