/* Automatically generated by subst.pl --- DO NOT EDIT!!! */

/*
 * FIDOGATE
 *
 * $Id: cf_env.c,v 4.18 2003/04/15 18:45:26 n0ll Exp $
 */

    if( (p = getenv("FIDOGATE_UUINBOUND")) )
        cf_s_uuinbound(p);
    if( (p = getenv("FIDOGATE_PASSWD")) )
        cf_s_passwd(p);
    if( (p = getenv("FIDOGATE_VARDIR")) )
        cf_s_vardir(p);
    if( (p = getenv("FIDOGATE_LOCKDIR")) )
        cf_s_lockdir(p);
    if( (p = getenv("FIDOGATE_INBOUND")) )
        cf_s_inbound(p);
    if( (p = getenv("FIDOGATE_BTBASEDIR")) )
        cf_s_btbasedir(p);
    if( (p = getenv("FIDOGATE_FTPINBOUND")) )
        cf_s_ftpinbound(p);
    if( (p = getenv("FIDOGATE_ALIASES")) )
        cf_s_aliases(p);
    if( (p = getenv("FIDOGATE_HOSTS")) )
        cf_s_hosts(p);
    if( (p = getenv("FIDOGATE_PINBOUND")) )
        cf_s_pinbound(p);
    if( (p = getenv("FIDOGATE_SPOOLDIR")) )
        cf_s_spooldir(p);
    if( (p = getenv("FIDOGATE_LIBDIR")) )
        cf_s_libdir(p);
    if( (p = getenv("FIDOGATE_HISTORY")) )
        cf_s_history(p);
    if( (p = getenv("FIDOGATE_LOGDIR")) )
        cf_s_logdir(p);
    if( (p = getenv("FIDOGATE_PACKING")) )
        cf_s_packing(p);
    if( (p = getenv("FIDOGATE_BINDIR")) )
        cf_s_bindir(p);
    if( (p = getenv("FIDOGATE_CONFIGDIR")) )
        cf_s_configdir(p);
    if( (p = getenv("FIDOGATE_CHARSETMAP")) )
        cf_s_charsetmap(p);
    if( (p = getenv("FIDOGATE_ACL")) )
        cf_s_acl(p);
    if( (p = getenv("FIDOGATE_LOGFILE")) )
        cf_s_logfile(p);
    if( (p = getenv("FIDOGATE_AREAS")) )
        cf_s_areas(p);
    if( (p = getenv("FIDOGATE_ROUTING")) )
        cf_s_routing(p);
