name: MacOS Build
on: [push]
jobs:
  build:
    name: MacOS Build
    runs-on: macOS-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          brew install automake bison gettext libiconv

      - name: Configure
        run: |
          ICONV_PREFIX="$(brew --prefix libiconv)"
          export CPPFLAGS="-I${ICONV_PREFIX}/include"
          export LDFLAGS="-L${ICONV_PREFIX}/lib"
          export LIBS="-liconv"
          AUTOPOINT="autopoint --force" ./autogen.sh
          ./configure --without-news --with-sendmail=/usr/sbin/sendmail --disable-extraversion
      - name: Build
        run: make V=1
